services:
  - type: web
    name: event-intelligence-backend
    env: python
    plan: free

    rootDir: Backend

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT

    pythonVersion: 3.12.0

    envVars:
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false
